name: Force Release

permissions: {}

on:
  workflow_dispatch:

jobs:
  force-release:
    name: Force release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: ffflorian/actions/force-release@347c23df6262a6482a59a1558f17f4f0b69249b1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run_command: 'npx semantic-release'
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
